/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "sidebar": "false,",
        "home": true,
        "heroText": "Hero",
        "tagline": "Hero 副标题",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5eec718d",
      "path": "/",
      "lastUpdated": "4/18/2021, 9:41:12 PM"
    },
    {
      "title": "关于我的内容",
      "frontmatter": {
        "sidebar": "auto",
        "sidebarDepth": 1
      },
      "regularPath": "/aboutme.html",
      "relativePath": "aboutme.md",
      "key": "v-3065a34e",
      "path": "/aboutme.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 3,
          "title": "四级标题",
          "slug": "四级标题"
        }
      ],
      "lastUpdated": "4/18/2021, 9:57:51 PM"
    },
    {
      "title": "欢迎来到分类",
      "frontmatter": {
        "sidebar": "auto",
        "sidebarDepth": 1
      },
      "regularPath": "/category.html",
      "relativePath": "category.md",
      "key": "v-3a1ffbc4",
      "path": "/category.html",
      "headers": [
        {
          "level": 2,
          "title": "标题二",
          "slug": "标题二"
        }
      ],
      "lastUpdated": "4/18/2021, 9:41:12 PM"
    },
    {
      "title": "我的项目",
      "frontmatter": {
        "sidebar": "auto",
        "sidebarDepth": 1
      },
      "regularPath": "/myproject.html",
      "relativePath": "myproject.md",
      "key": "v-d74b8de4",
      "path": "/myproject.html",
      "lastUpdated": "4/18/2021, 9:41:12 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间:",
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "分类",
        "link": "/category/"
      },
      {
        "text": "我的项目",
        "link": "/myproject/"
      },
      {
        "text": "友情链接",
        "ariaLabel": "Other Links",
        "items": [
          {
            "text": "MyGithub",
            "link": "https://github.com/jinfazhu-mygit"
          },
          {
            "text": "gitee",
            "link": "https://gitee.com/"
          },
          {
            "text": "aliyun",
            "link": "https://aliyun.com/"
          }
        ]
      },
      {
        "text": "关于我",
        "link": "/aboutme/"
      }
    ],
    "plugins": [
      [
        "@vuepress/last-updated",
        {}
      ]
    ]
  }
}